---
abstract: 'Audit log for authentication/authorization'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::HomeDir::Test: 0
  Module::Build: 0.3601
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PlugAuth-Plugin-Audit
requires:
  DateTime: 0
  File::HomeDir: 0
  Path::Class::Dir: 0
  Path::Class::File: 0
  PlugAuth: 0.09
  PlugAuth::Role::Plugin: 0
  Role::Tiny::With: 0
  YAML: 0
  perl: v5.10.0
version: 0.02
